import Head from "next/head";
import Image from "next/image";
// import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

// const inter = Inter({ subsets: ["latin"] });

export default function Home({ flavorText }: { flavor: string }) {
  return (
    <>
      {/* <Head>
        <title>ella.cx</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main className={styles.main}>
        <h1>Greetings, wanderer.</h1>
        <p>It appears as though you have stumbled upon my website.</p>
        <Image
          src="https://github.com/exu3.png"
          alt="Picture of the author"
          width={200}
          height={200}
        />
        <em>{flavorText.flavor}</em>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const flavorText = await fetch(
    `https://${process.env.VERCEL_URL}/api/flavor`
  ).then((res) => res.json());
  return {
    props: {
      flavorText,
    },
  };
}
